
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfzkuonqbkeirfwigksf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmemt1b25xYmtlaXJmd2lna3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjM5NjAsImV4cCI6MjA2NTczOTk2MH0.yVnOKGt5EvHX4quk_xtCtRWqO6SKHDCNRL7CY-ka1Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: { schema: 'public' },
  auth: { persistSession: true }
});

// Helper function to check connection
export async function checkSupabaseConnection() {
  try {
    const { error } = await supabase.from('contacts').select('count').limit(1);
    if (error?.code === 'PGRST200') {
      console.error('❌ שגיאה: Exposed Schemas לא מוגדר כ-public בהגדרות Supabase');
      return false;
    }
    return !error;
  } catch (err) {
    console.error('❌ בעיית חיבור ל-Supabase:', err);
    return false;
  }
}
